version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./uploads:/app/uploads  # Nutze ein lokales Verzeichnis für Uploads
