version: '3'

services:
  web:
    build: .
    restart: always
    expose:
      - "8000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    networks:
      - webnet
    volumes:
      - /app/uploads:/app/uploads  # Falls du Dateien hochlädst, kannst du Volumes nutzen

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx-Konfigurationsdatei
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html
    depends_on:
      - web
    networks:
      - webnet

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - LETSENCRYPT_EMAIL=youremail@example.com
      - LETSENCRYPT_HOST=yourdomain.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs:rw
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
